### ISSUE TITLE
Missing folder "MUSTARDSauce/subset_valid" in download file

### ISSUE THREAD

**Issue by Yukang-Lin** [Eleanor-H/MUSTARD#4]
Hi, thanks for your great work.
But it seems like the given generated data is missing the "subset_valid" directory. 
![image](https://github.com/user-attachments/assets/cf20bd7b-28f9-421d-b10e-ca3e433187ae)
I would be grateful if you could help check that.

**Comment by Eleanor-H** [comment]
Hi, thanks for the question! The `subset_filtered` directory is exactly the `subset_valid`. I'll update the README.
